name: Sync
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 'https://github.com/TBXark/ChatGPT-Telegram-Workers'
          destination_branch: 'master'
          github_token: ${{ secrets.CHATGPT_TELEGRAM_TOKEN }} 
          source_branch: 'master'
